export const sanitizeTextForPDF = (str: string | undefined | null): string => {
  if (!str) return '';
  return String(str)
    // Common composite math functions & notation
    .replace(/f⁻¹/g, 'f^-1')
    .replace(/f\^\{-1\}/g, 'f^-1')
    // Comparison operators
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/≠/g, '!=')
    .replace(/≈/g, '~=')
    .replace(/≡/g, '==')
    .replace(/±/g, '+/-')
    .replace(/∓/g, '-/+')
    .replace(/×/g, '*')
    .replace(/÷/g, '/')
    .replace(/√/g, 'sqrt')
    .replace(/∞/g, 'infinity')
    .replace(/∝/g, 'proportional to')
    // Superscripts
    .replace(/⁰/g, '^0')
    .replace(/¹/g, '^1')
    .replace(/²/g, '^2')
    .replace(/³/g, '^3')
    .replace(/⁴/g, '^4')
    .replace(/⁵/g, '^5')
    .replace(/⁶/g, '^6')
    .replace(/⁷/g, '^7')
    .replace(/⁸/g, '^8')
    .replace(/⁹/g, '^9')
    .replace(/⁺/g, '^+')
    .replace(/⁻/g, '^-')
    .replace(/⁼/g, '^=')
    .replace(/⁽/g, '^(')
    .replace(/⁾/g, '^)')
    .replace(/ⁿ/g, '^n')
    .replace(/ⁱ/g, '^i')
    .replace(/ˣ/g, '^x')
    // Subscripts
    .replace(/₀/g, '_0')
    .replace(/₁/g, '_1')
    .replace(/₂/g, '_2')
    .replace(/₃/g, '_3')
    .replace(/₄/g, '_4')
    .replace(/₅/g, '_5')
    .replace(/₆/g, '_6')
    .replace(/₇/g, '_7')
    .replace(/₈/g, '_8')
    .replace(/₉/g, '_9')
    .replace(/₊/g, '_+')
    .replace(/₋/g, '_-')
    .replace(/₌/g, '_=')
    .replace(/₍/g, '_(')
    .replace(/₎/g, '_)')
    .replace(/ₐ/g, '_a')
    .replace(/ₑ/g, '_e')
    .replace(/ₒ/g, '_o')
    .replace(/ₓ/g, '_x')
    // Set operations & logic
    .replace(/∈/g, ' in ')
    .replace(/∉/g, ' not in ')
    .replace(/⊂/g, ' subset of ')
    .replace(/⊆/g, ' subset or equal to ')
    .replace(/∪/g, ' union ')
    .replace(/∩/g, ' intersect ')
    .replace(/∅/g, 'empty set')
    // Arrows
    .replace(/→/g, '->')
    .replace(/←/g, '<-')
    .replace(/⇒/g, '=>')
    .replace(/⇔/g, '<=>')
    // Greek letters
    .replace(/π/g, 'pi')
    .replace(/Π/g, 'Pi')
    .replace(/θ/g, 'theta')
    .replace(/Θ/g, 'Theta')
    .replace(/α/g, 'alpha')
    .replace(/β/g, 'beta')
    .replace(/γ/g, 'gamma')
    .replace(/δ/g, 'delta')
    .replace(/Δ/g, 'Delta')
    .replace(/ε/g, 'epsilon')
    .replace(/λ/g, 'lambda')
    .replace(/μ/g, 'mu')
    .replace(/σ/g, 'sigma')
    .replace(/Σ/g, 'Sigma')
    .replace(/ω/g, 'omega')
    .replace(/Ω/g, 'Omega')
    // Quotes, dashes & bullets
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/…/g, '...')
    .replace(/—/g, '--')
    .replace(/–/g, '-')
    .replace(/•/g, '*')
    // Final fallback: strip any non-WinAnsi printable characters
    .replace(/[^\x00-\xFF]/g, '');
};
